server:
  port: ${PORT:8080}

spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:mdb-test.c6vunyturrl6.us-west-1.rds.amazonaws.com}:${DB_PORT:3306}/${DB_NAME:airline}?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USER:postulaciones}
    password: ${DB_PASS:post123456}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 10000
      validation-timeout: 3000
      connection-test-query: "SELECT 1"
      keepalive-time: 5000
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      mode: never

logging:
  level:
    org.springframework.jdbc.core: INFO
